-- BU KODU SUPABASE SQL EDITOR'E YAPIŞTIRIN VE RUN TUŞUNA BASIN

-- 1. PROFILES TABLOSU (Güvenli Oluşturma ve Güncelleme)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  username text,
  avatar_url text,
  is_blocked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Eksik sütunları ekle
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'is_blocked') then
    alter table public.profiles add column is_blocked boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'email') then
    alter table public.profiles add column email text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'avatar_url') then
    alter table public.profiles add column avatar_url text;
  end if;
end $$;

-- Profil RLS
alter table public.profiles enable row level security;
drop policy if exists "Profilleri herkes görebilir" on public.profiles;
create policy "Profilleri herkes görebilir" on public.profiles for select using (true);
drop policy if exists "Kullanıcılar kendi profilini güncelleyebilir" on public.profiles;
create policy "Kullanıcılar kendi profilini güncelleyebilir" on public.profiles for update using (auth.uid() = id);

-- 2. REVIEWS TABLOSU (YORUMLAR VE PUANLAR)
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id bigint not null,
  rating integer check (rating >= 1 and rating <= 10),
  comment text,
  has_spoiler boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.reviews drop constraint if exists reviews_user_id_movie_id_key;
alter table public.reviews add constraint reviews_user_id_movie_id_key unique (user_id, movie_id);

alter table public.reviews enable row level security;
drop policy if exists "Herkes yorumları okuyabilir" on public.reviews;
drop policy if exists "Kullanıcılar kendi yorumunu ekleyebilir" on public.reviews;
drop policy if exists "Kullanıcılar kendi yorumunu güncelleyebilir" on public.reviews;
drop policy if exists "Kullanıcılar kendi yorumunu silebilir" on public.reviews;
drop policy if exists "Review CRUD" on public.reviews;

create policy "Herkes yorumları okuyabilir" on public.reviews for select using (true);
create policy "Kullanıcılar kendi yorumunu ekleyebilir" on public.reviews for insert with check (auth.uid() = user_id);
create policy "Kullanıcılar kendi yorumunu güncelleyebilir" on public.reviews for update using (auth.uid() = user_id);
create policy "Kullanıcılar kendi yorumunu silebilir" on public.reviews for delete using (auth.uid() = user_id);

-- 3. KOLEKSİYONLAR
create table if not exists public.user_collections (
  id text not null primary key,
  user_id uuid references auth.users not null,
  name text not null,
  movies jsonb default '[]'::jsonb,
  top_favorite_movies jsonb default '[null, null, null, null, null]'::jsonb,
  top_favorite_shows jsonb default '[null, null, null, null, null]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_collections enable row level security;
drop policy if exists "Koleksiyon CRUD" on public.user_collections;
create policy "Koleksiyon CRUD" on public.user_collections for all using (auth.uid() = user_id);

-- 4. PAYLAŞILAN LİSTELER (Özel ID formatı için düzenlendi)
-- Eski tablo varsa kaldır (UUID çakışmasını önlemek için)
drop table if exists public.shared_lists;

create table public.shared_lists (
  id text primary key, -- UUID yerine TEXT (XXXX-XXXX-XXXX-XXXX formatı için)
  user_id uuid references auth.users not null,
  name text not null,
  movies jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.shared_lists enable row level security;
drop policy if exists "Public Read Shared" on public.shared_lists;
create policy "Public Read Shared" on public.shared_lists for select using (true);
drop policy if exists "User Insert Shared" on public.shared_lists;
create policy "User Insert Shared" on public.shared_lists for insert with check (auth.uid() = user_id);

-- 5. TRIGGER (Otomatik Profil Oluşturma)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, avatar_url)
  values (
      new.id,
      new.email,
      coalesce(new.raw_user_meta_data->>'username', new.email),
      new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing; 
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. HESAP SİLME FONKSİYONU
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;