-- BU KODU SUPABASE SQL EDITOR'E YAPIŞTIRIN VE RUN TUŞUNA BASIN

-- 1. PROFILES TABLOSU (Güvenli Oluşturma ve Güncelleme)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  username text,
  is_blocked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Eksik sütunları ekle (Tablo zaten varsa ve sütun yoksa ekler)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'is_blocked') then
    alter table public.profiles add column is_blocked boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'email') then
    alter table public.profiles add column email text;
  end if;
end $$;

-- RLS (Güvenlik Kuralları - Öncekileri temizleyip yeniden kurar)
alter table public.profiles enable row level security;

drop policy if exists "Profilleri herkes görebilir" on public.profiles;
create policy "Profilleri herkes görebilir" on public.profiles for select using (true);

drop policy if exists "Kullanıcılar kendi profilini güncelleyebilir" on public.profiles;
create policy "Kullanıcılar kendi profilini güncelleyebilir" on public.profiles for update using (auth.uid() = id);

-- 2. REVIEWS TABLOSU
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id bigint not null,
  rating integer check (rating >= 1 and rating <= 10),
  comment text,
  has_spoiler boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, movie_id)
);

alter table public.reviews enable row level security;

drop policy if exists "Herkes yorumları okuyabilir" on public.reviews;
create policy "Herkes yorumları okuyabilir" on public.reviews for select using (true);

drop policy if exists "Sadece sahibi ekleyebilir" on public.reviews;
create policy "Sadece sahibi ekleyebilir" on public.reviews for insert with check (auth.uid() = user_id);

drop policy if exists "Sadece sahibi düzenleyebilir" on public.reviews;
create policy "Sadece sahibi düzenleyebilir" on public.reviews for update using (auth.uid() = user_id);

drop policy if exists "Sadece sahibi silebilir" on public.reviews;
create policy "Sadece sahibi silebilir" on public.reviews for delete using (auth.uid() = user_id);

-- 3. KOLEKSİYONLAR
create table if not exists public.user_collections (
  id text not null primary key,
  user_id uuid references auth.users not null,
  name text not null,
  movies jsonb default '[]'::jsonb,
  top_favorite_movies jsonb default '[null, null, null, null, null]'::jsonb,
  top_favorite_shows jsonb default '[null, null, null, null, null]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_collections enable row level security;

drop policy if exists "Koleksiyon CRUD" on public.user_collections;
create policy "Koleksiyon CRUD" on public.user_collections for all using (auth.uid() = user_id);

-- 4. PAYLAŞILAN LİSTELER
create table if not exists public.shared_lists (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  name text not null,
  movies jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.shared_lists enable row level security;

drop policy if exists "Public Read Shared" on public.shared_lists;
create policy "Public Read Shared" on public.shared_lists for select using (true);

drop policy if exists "User Insert Shared" on public.shared_lists;
create policy "User Insert Shared" on public.shared_lists for insert with check (auth.uid() = user_id);

-- 5. TRIGGER (Kullanıcı oluşunca profil oluşturma)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (
      new.id,
      new.email,
      coalesce(new.raw_user_meta_data->>'username', new.email)
  )
  on conflict (id) do nothing; -- Zaten varsa hata verme
  return new;
end;
$$ language plpgsql security definer;

-- Trigger varsa silip yeniden oluşturur
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. ESKİ KULLANICILARI DÜZELTME (Opsiyonel)
-- Eğer trigger'dan önce oluşturulmuş kullanıcılar varsa onları da ekler
insert into public.profiles (id, email, username)
select id, email, raw_user_meta_data->>'username'
from auth.users
on conflict (id) do nothing;